### ISSUE TITLE
maven pom is chinese?

### ISSUE THREAD

**Issue by JanGroot** [hashimati/Microstarter#2]
[myappb.zip](https://github.com/hashimati/microstarter/files/3331613/myappb.zip)

After generating a project with a maven java 12 target on a mac on laterst macos, the 
pom is encoded wrongly. 
It seems chinese in my editor, expected something in the line of utf-8 xml..

**Comment by hashimati** [comment]
Hi Sir,

Could you tell me the name of the editor + version please.

Thanks

**Comment by JanGroot** [comment]
Ah, missed this, sorry, intellij on Mac
